
# _for_loop_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FOR ID IN LBRACE LPAREN NUMBER RANGE RBRACE RPARENstatement : FOR ID IN RANGE LPAREN NUMBER RPAREN LBRACE statement RBRACEstatement : ID'

_lr_action_items = {'FOR':([0,10,],[2,2,]),'ID':([0,2,10,],[3,4,3,]),'$end':([1,3,12,],[0,-2,-1,]),'RBRACE':([3,11,12,],[-2,12,-1,]),'IN':([4,],[5,]),'RANGE':([5,],[6,]),'LPAREN':([6,],[7,]),'NUMBER':([7,],[8,]),'RPAREN':([8,],[9,]),'LBRACE':([9,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,10,],[1,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> FOR ID IN RANGE LPAREN NUMBER RPAREN LBRACE statement RBRACE','statement',10,'p_statement_for','for_loop_parser.py',5),
  ('statement -> ID','statement',1,'p_statement_expr','for_loop_parser.py',9),
]
