
# _variable_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID NUMBER STRINGstatement : ID EQUALS expressionexpression : NUMBERexpression : STRING'

_lr_action_items = {'ID':([0,],[2,]),'$end':([1,4,5,6,],[0,-1,-2,-3,]),'EQUALS':([2,],[3,]),'NUMBER':([3,],[5,]),'STRING':([3,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID EQUALS expression','statement',3,'p_statement_assign','variable_parser.py',5),
  ('expression -> NUMBER','expression',1,'p_expression_number','variable_parser.py',9),
  ('expression -> STRING','expression',1,'p_expression_string','variable_parser.py',13),
]
