
# _while_loop_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID LBRACE LPAREN NUMBER OPERATOR RBRACE RPAREN WHILEstatement : WHILE LPAREN condition RPAREN LBRACE statement RBRACEcondition : ID OPERATOR expressionexpression : IDexpression : NUMBERstatement : ID'

_lr_action_items = {'WHILE':([0,9,],[2,2,]),'ID':([0,4,8,9,],[3,6,10,3,]),'$end':([1,3,14,],[0,-5,-1,]),'LPAREN':([2,],[4,]),'RBRACE':([3,13,14,],[-5,14,-1,]),'RPAREN':([5,10,11,12,],[7,-3,-2,-4,]),'OPERATOR':([6,],[8,]),'LBRACE':([7,],[9,]),'NUMBER':([8,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,9,],[1,13,]),'condition':([4,],[5,]),'expression':([8,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> WHILE LPAREN condition RPAREN LBRACE statement RBRACE','statement',7,'p_statement_while','while_loop_parser.py',5),
  ('condition -> ID OPERATOR expression','condition',3,'p_condition','while_loop_parser.py',9),
  ('expression -> ID','expression',1,'p_expression_id','while_loop_parser.py',13),
  ('expression -> NUMBER','expression',1,'p_expression_number','while_loop_parser.py',17),
  ('statement -> ID','statement',1,'p_statement_expr','while_loop_parser.py',21),
]
